{"name": "# C5188 Device Dashboard page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1048, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1602389269881, "stop": 1602389272714}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1602389272714, "stop": 1602389275599}, {"name": "And Go to the Devices page https://devcloud.connectedio.com/devices", "status": "passed", "start": 1602389275600, "stop": 1602389275758}, {"name": "Then Click Add new device button on the right up corner", "status": "passed", "start": 1602389275758, "stop": 1602389276154}, {"name": "Then Fill required Device IMEI field 356961071557824", "status": "passed", "start": 1602389276155, "stop": 1602389276349}, {"name": "And Fill Device Name field if any TVM Test123 jjnkjn", "status": "passed", "start": 1602389276350, "stop": 1602389276545}, {"name": "Then Fill required Serial Number field 1806208A0279", "status": "passed", "start": 1602389276545, "stop": 1602389276686}, {"name": "And Click Save and refresh the page", "status": "passed", "start": 1602389276687, "stop": 1602389277959}, {"name": "Then Success is here - device is on the page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1048, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1602389277959, "stop": 1602389296128}, {"name": "Then Choose any device with IMEI number which is highlighted in blue active IMEI number and click on an active IMEI number", "status": "skipped", "start": 1602389298232, "stop": 1602389298232}, {"name": "Then Verify the Device Management Portal has opened", "status": "skipped", "start": 1602389298232, "stop": 1602389298232}], "start": 1602389264563, "stop": 1602389298232, "uuid": "4b312b7b-6faa-4490-aa25-f6c6ac68a100", "historyId": "06f5543c6cdade6c93c93ff17d488c0a", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5188 Device Dashboard page"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}