{"name": "# C5152 Verify if the Device offline card is working", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5152_Verify_if_the_Device_offline_card_is_working.py\", line 8, in clk_dvcs_onlc\n    context.app.main_page.clk_dvcs_onlc()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 529, in clk_dvcs_onlc\n    wait.until(EC.element_to_be_clickable(DVCS_OFFLN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1600649082815, "stop": 1600649085402}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1600649085402, "stop": 1600649090209}, {"name": "Then Click on DEVICE OFFLINE card", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5152_Verify_if_the_Device_offline_card_is_working.py\", line 8, in clk_dvcs_onlc\n    context.app.main_page.clk_dvcs_onlc()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 529, in clk_dvcs_onlc\n    wait.until(EC.element_to_be_clickable(DVCS_OFFLN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1600649090209, "stop": 1600649108506}, {"name": "And https://devcloud.connectedio.com/devices is here", "status": "skipped", "start": 1600649110623, "stop": 1600649110623}, {"name": "Then Verify Offline status in FILTERS field is seen", "status": "skipped", "start": 1600649110623, "stop": 1600649110623}], "start": 1600649077433, "stop": 1600649110623, "uuid": "b425c1a9-2229-4492-98d1-6c956091402a", "historyId": "eb7d915b408c8a8ca953391c2e2f18e1", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5152 Verify if the Device offline card is working"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}