{"name": "# Add New User", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button _ngcontent-ysi-c8=\"\" aria-haspopup=\"true\" class=\"btn btn-default btn-sm dropdown-toggle dropdown-toggle\" ngbdropdowntoggle=\"\" type=\"button\" aria-expanded=\"false\">...</button> is not clickable at point (1181, 77). Other element would receive the click: <div _ngcontent-ysi-c8=\"\" class=\"spinner-outer ng-star-inserted\">...</div>\n  (Session info: chrome=85.0.4183.83)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 29, in clck_qck_actns_btn\n    context.app.main_page.clck_qck_actns_btn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 56, in clck_qck_actns_btn\n    wait.until(EC.element_to_be_clickable(QUICK_ACTIONS)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1599612608572, "stop": 1599612613040}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1599612613040, "stop": 1599612613909}, {"name": "Then Click on the Users button", "status": "passed", "start": 1599612613909, "stop": 1599612614959}, {"name": "Then Click on the Quick actions button", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <button _ngcontent-ysi-c8=\"\" aria-haspopup=\"true\" class=\"btn btn-default btn-sm dropdown-toggle dropdown-toggle\" ngbdropdowntoggle=\"\" type=\"button\" aria-expanded=\"false\">...</button> is not clickable at point (1181, 77). Other element would receive the click: <div _ngcontent-ysi-c8=\"\" class=\"spinner-outer ng-star-inserted\">...</div>\n  (Session info: chrome=85.0.4183.83)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 29, in clck_qck_actns_btn\n    context.app.main_page.clck_qck_actns_btn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 56, in clck_qck_actns_btn\n    wait.until(EC.element_to_be_clickable(QUICK_ACTIONS)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1599612614960, "stop": 1599612616130}, {"name": "Then Select Add in the drop-down menu", "status": "skipped", "start": 1599612618278, "stop": 1599612618278}, {"name": "Then Fill out the required fields", "status": "skipped", "start": 1599612618278, "stop": 1599612618278}, {"name": "And Click on the Add button", "status": "skipped", "start": 1599612618278, "stop": 1599612618278}, {"name": "Then Verify user Roman Ivanov is here", "status": "skipped", "start": 1599612618278, "stop": 1599612618278}], "start": 1599612603241, "stop": 1599612618278, "uuid": "95fcfa5c-b622-460c-8999-8a7ba3462aa2", "historyId": "5ebd76dc263ad2277f7fee84ef3bcb25", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# Add New User"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}