{"name": "# C5440 Delete User", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (-125, 361)\n  (Session info: headless chrome=85.0.4183.121)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 22, in clck_usrs_btn\n    context.app.main_page.clck_usrs_btn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 114, in clck_usrs_btn\n    wait.until(EC.element_to_be_clickable(USERS)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1601610299987, "stop": 1601610302938}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1601610302938, "stop": 1601610307894}, {"name": "Then Click on the Users button", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element is not clickable at point (-125, 361)\n  (Session info: headless chrome=85.0.4183.121)\n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 22, in clck_usrs_btn\n    context.app.main_page.clck_usrs_btn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 114, in clck_usrs_btn\n    wait.until(EC.element_to_be_clickable(USERS)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 80, in click\n    self._execute(Command.CLICK_ELEMENT)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webelement.py\", line 633, in _execute\n    return self._parent.execute(command, params)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1601610307894, "stop": 1601610308983}, {"name": "Then Make sure there are at least two Admins and one User role in the list of users", "status": "skipped", "start": 1601610311029, "stop": 1601610311029}, {"name": "Then Click on the Settings 'three vertical' dots from the rightmost side of the user", "status": "skipped", "start": 1601610311029, "stop": 1601610311029}, {"name": "Then Choose and click on 'Delete' from the dropdown menu", "status": "skipped", "start": 1601610311029, "stop": 1601610311029}, {"name": "Then Confirm action by clicking OK button on the pop-up dialog window", "status": "skipped", "start": 1601610311029, "stop": 1601610311029}, {"name": "Then Then Verify that there is for one user less after deleting", "status": "skipped", "start": 1601610311029, "stop": 1601610311029}], "start": 1601610294873, "stop": 1601610311029, "uuid": "9efc9865-7297-48fe-b27d-0bcf7436f763", "historyId": "052d21b30082a18d0bb410aa5def4f94", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5440 Delete User"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}