{"name": "# C5157 Verify if the Data usage card is rotating", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5157_Verify_if_the_Data_usage_card_is_rotating.py\", line 16, in cllr_or_wan_txts_hr\n    context.app.main_page.cllr_or_wan_txts_hr()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 680, in cllr_or_wan_txts_hr\n    cllr_txt = wait.until(EC.visibility_of_element_located(CLLR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1605383576987, "stop": 1605383590139}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1605383590139, "stop": 1605383592988}, {"name": "Then Click on the DATA USAGE card with Cellular data used", "status": "passed", "start": 1605383592988, "stop": 1605383593089}, {"name": "Then Verify that the DATA USAGE card has rotated to WAN data used and he DATA USAGE card has rotated back to Cellular data used", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5157_Verify_if_the_Data_usage_card_is_rotating.py\", line 16, in cllr_or_wan_txts_hr\n    context.app.main_page.cllr_or_wan_txts_hr()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 680, in cllr_or_wan_txts_hr\n    cllr_txt = wait.until(EC.visibility_of_element_located(CLLR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1605383593089, "stop": 1605383611298}], "start": 1605383571731, "stop": 1605383613395, "uuid": "57000ff6-9feb-48f0-a203-60c6b8dd227e", "historyId": "0df2df740e2c56cf04bb1264ddca1248", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5157 Verify if the Data usage card is rotating"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}