{"name": "# C5177 Add a new device that has already registered in the system", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5177_Add_a_new_device_that_has_already registered_in_the_system.py\", line 16, in systm_vrfctn_dvc_alrd_exsts\n    context.app.main_page.systm_vrfctn_dvc_alrd_exsts()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1115, in systm_vrfctn_dvc_alrd_exsts\n    wait.until(EC.invisibility_of_element_located(DVC_ALRD_EXSTS))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1602319076513, "stop": 1602319079342}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1602319079342, "stop": 1602319082190}, {"name": "And Go to the Devices page https://devcloud.connectedio.com/devices", "status": "passed", "start": 1602319082190, "stop": 1602319082384}, {"name": "Then Click Add new device button on the right up corner", "status": "passed", "start": 1602319082385, "stop": 1602319083000}, {"name": "Then Fill required Device IMEI field 356961071557824", "status": "passed", "start": 1602319083000, "stop": 1602319083201}, {"name": "And Fill Device Name field if any TVM Test123 jjnkjn", "status": "passed", "start": 1602319083202, "stop": 1602319083402}, {"name": "Then Fill required Serial Number field 1806208A0279", "status": "passed", "start": 1602319083402, "stop": 1602319083528}, {"name": "And Click Save and refresh the page", "status": "passed", "start": 1602319083528, "stop": 1602319085289}, {"name": "Then Success is here - device is on the page", "status": "passed", "start": 1602319085289, "stop": 1602319087080}, {"name": "Then Add a new device that has already registered in the system", "status": "passed", "start": 1602319087080, "stop": 1602319090874}, {"name": "Then The system should check if the device has already registered a prompt should appear Device already exists", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5177_Add_a_new_device_that_has_already registered_in_the_system.py\", line 16, in systm_vrfctn_dvc_alrd_exsts\n    context.app.main_page.systm_vrfctn_dvc_alrd_exsts()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1115, in systm_vrfctn_dvc_alrd_exsts\n    wait.until(EC.invisibility_of_element_located(DVC_ALRD_EXSTS))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1602319090875, "stop": 1602319106616}], "start": 1602319071141, "stop": 1602319108735, "uuid": "338b9308-2953-400d-a50d-adf9ab9763eb", "historyId": "b595c97d934ae9dff1c5f5d73f8298ad", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5177 Add a new device that has already registered in the system"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}