{"name": "# C5177 Add a new device that has already registered in the system", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1064, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1603148425181, "stop": 1603148428459}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1603148428459, "stop": 1603148431469}, {"name": "And Go to the Devices page https://devcloud.connectedio.com/devices", "status": "passed", "start": 1603148431469, "stop": 1603148431655}, {"name": "Then Click Add new device button on the right up corner", "status": "passed", "start": 1603148431655, "stop": 1603148432094}, {"name": "Then Fill required Device IMEI field 356961071557824", "status": "passed", "start": 1603148432094, "stop": 1603148432280}, {"name": "And Fill Device Name field if any TVM Test123 jjnkjn", "status": "passed", "start": 1603148432281, "stop": 1603148432471}, {"name": "Then Fill required Serial Number field 1806208A0279", "status": "passed", "start": 1603148432471, "stop": 1603148432637}, {"name": "And Click Save and refresh the page", "status": "passed", "start": 1603148432638, "stop": 1603148433922}, {"name": "Then Success is here - device is on the page", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5176_Add_a_new_device.py\", line 56, in dvc_is_on_the_pg\n    context.app.main_page.dvc_is_on_the_pg()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 1064, in dvc_is_on_the_pg\n    actual_text = wait.until(EC.visibility_of_element_located(IMEI_HR)).text\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1603148433922, "stop": 1603148452042}, {"name": "Then Add a new device that has already registered in the system", "status": "skipped", "start": 1603148454171, "stop": 1603148454171}, {"name": "Then The system should check if the device has already registered a prompt should appear Device already exists", "status": "skipped", "start": 1603148454171, "stop": 1603148454171}], "start": 1603148419768, "stop": 1603148454171, "uuid": "584a8ecc-312b-499b-a482-4bdc1de86624", "historyId": "b595c97d934ae9dff1c5f5d73f8298ad", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5177 Add a new device that has already registered in the system"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}