{"name": "# C5176 Add a new device", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 173, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1604923026333, "stop": 1604923029500}, {"name": "Then Login with the given credentials", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5472_Add_new_user.py\", line 15, in lgn_w_gn_crdntls\n    context.app.main_page.lgn_w_gn_crdntls()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 173, in lgn_w_gn_crdntls\n    wait.until(EC.element_to_be_clickable(POP_UP_WNDW_OK_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1604923029500, "stop": 1604923043424}, {"name": "And Go to the Devices page https://devcloud.connectedio.com/devices", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}, {"name": "Then Click Add new device button on the right up corner", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}, {"name": "Then Fill required Device IMEI field 356961071557824", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}, {"name": "And Fill Device Name field if any TVM Test123 jjnkjn", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}, {"name": "Then Fill required Serial Number field 1806208A0279", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}, {"name": "And Click Save and refresh the page", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}, {"name": "Then Success is here - device is on the page", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}, {"name": "Then Delete device", "status": "skipped", "start": 1604923045677, "stop": 1604923045677}], "start": 1604923020706, "stop": 1604923045677, "uuid": "dfb90839-204b-46c8-ac70-4b8a895a330f", "historyId": "f66297f0cc4ca767f9caf1684373e3ca", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5176 Add a new device"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}