{"name": "# C5440 Delete User", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5440_Delete_user.py\", line 24, in dlt_drp_dwn_mn\n    context.app.main_page.dlt_drp_dwn_mn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 179, in dlt_drp_dwn_mn\n    wait.until(EC.visibility_of_element_located(DELETE_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1600130845717, "stop": 1600130848372}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1600130848372, "stop": 1600130849280}, {"name": "Then Click on the Users button", "status": "passed", "start": 1600130849281, "stop": 1600130850370}, {"name": "Then Make sure there are at least two Admins and one User role in the list of users", "status": "passed", "start": 1600130850370, "stop": 1600130850873}, {"name": "Then Click on the Settings 'three vertical' dots from the rightmost side of the user", "status": "passed", "start": 1600130850873, "stop": 1600130850959}, {"name": "Then Choose and click on 'Delete' from the dropdown menu", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5440_Delete_user.py\", line 24, in dlt_drp_dwn_mn\n    context.app.main_page.dlt_drp_dwn_mn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 179, in dlt_drp_dwn_mn\n    wait.until(EC.visibility_of_element_located(DELETE_BTN)).click()\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1600130850959, "stop": 1600130869138}, {"name": "Then Confirm action by clicking OK button on the pop-up dialog window", "status": "skipped", "start": 1600130871259, "stop": 1600130871259}, {"name": "Then Then Verify that there is for one user less after deleting", "status": "skipped", "start": 1600130871259, "stop": 1600130871259}], "start": 1600130840367, "stop": 1600130871259, "uuid": "1ee6cb7d-9222-4082-905d-eea8a67a9505", "historyId": "052d21b30082a18d0bb410aa5def4f94", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5440 Delete User"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}