{"name": "# C5121 Logout from_the_Header and verify the login page will open after logout", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5121_Logout_from_the_Header.py\", line 8, in clck_hdr_lgt_btn\n    context.app.main_page.clck_hdr_lgt_btn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 300, in clck_hdr_lgt_btn\n    target = wait.until(EC.element_to_be_clickable(CLCK_LGT))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "steps": [{"name": "Given Loginpage", "status": "passed", "start": 1600649165370, "stop": 1600649168240}, {"name": "Then Login with the given credentials", "status": "passed", "start": 1600649168241, "stop": 1600649173206}, {"name": "Then Hover over the Logout button at the right corner of the Header and click on the button Logout", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.TimeoutException: Message: \n\n", "trace": "  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\model.py\", line 1329, in run\n    match.run(runner.context)\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\behave\\matchers.py\", line 98, in run\n    self.func(context, *args, **kwargs)\n  File \"features\\steps\\C5121_Logout_from_the_Header.py\", line 8, in clck_hdr_lgt_btn\n    context.app.main_page.clck_hdr_lgt_btn()\n  File \"C:\\Everything\\IT\\Testing\\Automation_08_09_2019\\UIautomation_python\\pages\\main_page.py\", line 300, in clck_hdr_lgt_btn\n    target = wait.until(EC.element_to_be_clickable(CLCK_LGT))\n  File \"c:\\users\\rapid\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\selenium\\webdriver\\support\\wait.py\", line 80, in until\n    raise TimeoutException(message, screen, stacktrace)\n"}, "start": 1600649173206, "stop": 1600649191380}, {"name": "And https://devcloud.connectedio.com/login is open after logout", "status": "skipped", "start": 1600649193498, "stop": 1600649193498}], "start": 1600649160008, "stop": 1600649193498, "uuid": "c3df52c9-9a6f-47fd-aa74-60afa159bce0", "historyId": "5195210d41c1c882304aa237be7bc9a5", "labels": [{"name": "severity", "value": "normal"}, {"name": "feature", "value": "# C5121 Logout from_the_Header"}, {"name": "framework", "value": "behave"}, {"name": "language", "value": "cpython3"}]}